spring:
  datasource:
    url: jdbc:mysql://192.168.66.100:3306/gulimail_sms
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: gulimail-coupon
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.66.100:8848
      server-addr: 192.168.66.100:8848
  config:
    import:
      - nacos:gulimail-coupon.properties?refreshEnabled=true


mybatis-plus:
  check-config-location: false
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath*:/mapper/**/*.xml

server:
  port: 7000
